### ISSUE TITLE
Monterey install ends in a boot loop

### ISSUE THREAD

**Issue by ScrewedDriver** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#66] opened 2021-10-29 14:24 UTC
The Installation of Monterey ends in a boot loop.
After a restart a black screen appears which says thet a needed firmware update could not be installed.

T450 i5
8GB RAM

**Comment by V3ntus** [comment] 2021-10-29 21:22
Logs? Verbose mode?

**Comment by racka98** [comment] 2021-10-30 03:14
Unfortunately I haven't had time to update this repo or test out Monterey

**Comment by dem55** [comment] 2021-10-30 17:01
I have same issue. During installation when 12 min left every time I've got this error.  
![image](https://user-images.githubusercontent.com/93395933/139542169-204aa961-e810-4858-9c6b-82dad36f894e.png)

**Comment by V3ntus** [comment] 2021-10-30 17:09
> I have same issue. During installation when 12 min left I've got this error.  
> Lenovo T450.
> Monterey 12.01
> ![image](https://user-images.githubusercontent.com/93395933/139542169-204aa961-e810-4858-9c6b-82dad36f894e.png)

I think you'll need to update to OpenCore 0.7+, unless you've already updated OC, the EFIs, and kexts

**Comment by dem55** [comment] 2021-10-30 17:26
> > I have same issue. During installation when 12 min left I've got this error.
> > Lenovo T450.
> > Monterey 12.01
> 
> I think you'll need to update to OpenCore 0.7+, unless you've already updated OC, the EFIs, and kexts

I use latest release. 
![image](https://user-images.githubusercontent.com/93395933/139542899-d0b57c98-998f-4f3e-84fd-b030c1aa968c.png)

**Comment by luanmateuz** [comment] 2021-11-02 19:41
I'm using the latest version of OC and it still has the same error.

`A required firmware update could not be installed.`

**Comment by buraktamturk** [comment] 2021-11-03 01:55
Apparently error is caused by a missing firmware feature flag required since Monterey Beta 7 and is fixed in OC 0.7.5
Since this flag is missing, the os installer tries to flash a new firmware and fails.

**Comment by CS6** [comment] 2021-11-09 08:34
@buraktamturk 
Sorry for stupid question
How to modify [0.7.5 CO](https://github.com/acidanthera/OpenCorePkg/releases/tag/0.7.5
) for [T450 0.7.0 CO](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/releases/tag/Mont-OC-0.7.0v1)

I tried some things, but it always shows
Replace OpenCore.efi & BOOTx64.efi based on [T450 0.7.0 CO](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/releases/tag/Mont-OC-0.7.0v1)
`OC: grabbed zero system-id for SB, this is not allowed. `....os sad

**Comment by CS6** [comment] 2021-11-09 12:17
My savior 🎉

https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/tree/master/EFI

**Comment by buraktamturk** [comment] 2021-11-09 15:16
Hello @CS6, could you post your result with that EFI file here? I also want to upgrade but was waiting for an update on this repository.

**Comment by CS6** [comment] 2021-11-10 08:21
@buraktamturk 
Please use this[ EFI directly](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/tree/master/EFI)
I have successfully installed it, only WIFI (7265) remains to be processed

**Comment by V3ntus** [comment] 2021-11-10 13:22
@CS6 
I've been using the CLAYBIOS EFI as well. Working great. Had to do some extra steps for my Intel wifi, but that just required some googling (how to add a kext in config.plist and the required Intel wifi+bt kext)

**Comment by racka98** [comment] 2021-11-11 06:10
I no longer have that laptop so unfortunately I can no longer offer support for this repo

**Closed by racka98** 2021-11-11 06:10 UTC
