### ISSUE TITLE
macOS Catalina to Monterey

### ISSUE THREAD

**Issue by luanmateuz** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#67] opened 2021-11-02 18:15 UTC
Well, I tried to upgrade from macOS Catalina to Monterey, but I have this problem.

I did it through System Preferences -> Software Update, however when the notebook (Thinkpad T450) restarts and starts the update process this error occurs.

`A required firmware update could not be installed.`

Is there any way to solve this problem?

![download](https://user-images.githubusercontent.com/58707019/139921099-5b36596e-4ad9-4961-ba37-36bd2ed08f4f.jpeg)

**Comment by V3ntus** [comment] 2021-11-02 18:22
Duplicate of #66

**Closed** 2021-11-02 19:05 UTC
